services:
  server:
    image: asw-bonus
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      VITE_PORT: "5173"

      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5173:5173"
    volumes:
      - ./src:/src
      - /src/node_modules